name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: github-analytics
  cancel-in-progress: true

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: Platane/snk@v3
        with:
          github_user_name: BhattAyush17
          outputs: |
            assets/snake/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=white&color_dots=#161b22,#4d4d4d,#808080,#b3b3b3,#e6e6e6

      - name: Sync latest branch
        run: |
          git pull --rebase origin main

      - name: Commit generated snake
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update contribution snake"
